Repository KEA-ChunSam/PlayUs-user-service, pull requests merged in 2025-06, with the labels that each got.

#54 Cs 362 fix/sse 구독 이후 알림 전송 수정
  src/main/java/com/playus/userservice/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/playus/userservice/domain/notification/service/NotificationService.java
  src/main/java/com/playus/userservice/global/config/SecurityConfig.java
Labels: ✨ feature, 🐛 bug

#78 Cs 407 fix/authorization request 저장소 변경
  src/main/java/com/playus/userservice/domain/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/playus/userservice/domain/oauth/util/CookieUtils.java
  src/main/java/com/playus/userservice/global/config/SecurityConfig.java
Labels: 예찬, 🐛 bug

#82 CS-410 Fix/쿠키 도메인 오탈자 수정
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 예찬, 🐛 bug

#86 CS-429 Refactor/프로필 변경 로직 변경
  src/main/java/com/playus/userservice/domain/user/controller/UserController.java
  src/main/java/com/playus/userservice/domain/user/dto/nickname/ProfileUpdateRequest.java
  src/main/java/com/playus/userservice/domain/user/service/ProfileSetupService.java
  src/main/java/com/playus/userservice/domain/user/service/UserService.java
  src/main/java/com/playus/userservice/domain/user/specification/UserControllerSpecification.java
  src/test/java/com/playus/userservice/domain/user/controller/UserControllerTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserServiceTest.java
Labels: ♻️ refactor, 예찬
