Repository KEA-ChunSam/PlayUs-user-service, pull requests merged in 2025-05, with the labels that each got.

#14 Cs 190 feat/kakao oauth 추가
  build.gradle
  src/main/java/com/playus/userservice/UserServiceApplication.java
  src/main/java/com/playus/userservice/domain/config/CorsConfig.java
  src/main/java/com/playus/userservice/domain/config/RedisConfig.java
  src/main/java/com/playus/userservice/domain/config/SecurityConfig.java
  src/main/java/com/playus/userservice/domain/config/mongo/MongoConfig.java
  src/main/java/com/playus/userservice/domain/oauth/controller/TokenController.java
  src/main/java/com/playus/userservice/domain/oauth/dto/CustomOAuth2User.java
  src/main/java/com/playus/userservice/domain/oauth/dto/KakaoResponse.java
  src/main/java/com/playus/userservice/domain/oauth/dto/OAuth2Response.java
  src/main/java/com/playus/userservice/domain/oauth/enums/TokenType.java
  src/main/java/com/playus/userservice/domain/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/playus/userservice/domain/oauth/service/AuthService.java
  src/main/java/com/playus/userservice/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/playus/userservice/domain/oauth/service/TokenService.java
  src/main/java/com/playus/userservice/domain/report/entity/Report.java
  src/main/java/com/playus/userservice/domain/user/document/NotificationDocument.java
  src/main/java/com/playus/userservice/domain/user/document/UserDocument.java
  src/main/java/com/playus/userservice/domain/user/document/UserTagDocument.java
  src/main/java/com/playus/userservice/domain/user/dto/UserDto.java
  src/main/java/com/playus/userservice/domain/user/entity/Tag.java
  src/main/java/com/playus/userservice/domain/user/entity/User.java
  src/main/java/com/playus/userservice/domain/user/repository/write/UserRepository.java
  src/main/java/com/playus/userservice/global/GlobalControllerAdvice.java
  src/main/java/com/playus/userservice/global/jwt/JwtFilter.java
  src/main/java/com/playus/userservice/global/jwt/JwtUtil.java
  src/main/java/com/playus/userservice/global/response/ErrorResponse.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: ✨ feature

#29 Cs 248 chore/sentry 도입
  build.gradle
  src/main/java/com/playus/userservice/global/config/CorsConfig.java
  src/main/java/com/playus/userservice/global/config/SecurityConfig.java
  src/main/java/com/playus/userservice/global/config/data/AuditingConfig.java
  src/main/java/com/playus/userservice/global/config/data/jpa/JpaConfig.java
  src/main/java/com/playus/userservice/global/config/data/mongodb/MongoConfig.java
  src/main/java/com/playus/userservice/global/config/data/mongodb/ReadMongoConfig.java
  src/main/java/com/playus/userservice/global/config/data/redis/RedisConfig.java
  src/main/java/com/playus/userservice/global/config/sentry/SentryConfig.java
  src/main/java/com/playus/userservice/global/config/swagger/SwaggerConfig.java
  src/main/java/com/playus/userservice/global/exception/ExceptionAdvice.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/logback-spring.xml
Labels: ⚙️ chore, 예찬

#32 Cs 257 feat/선호팀 및 닉네임 입력
  build.gradle
  src/main/java/com/playus/userservice/UserServiceApplication.java
  src/main/java/com/playus/userservice/domain/oauth/controller/AuthController.java
  src/main/java/com/playus/userservice/domain/oauth/controller/TokenController.java
  src/main/java/com/playus/userservice/domain/oauth/dto/CustomOAuth2User.java
  src/main/java/com/playus/userservice/domain/oauth/handler/CustomFailureHandler.java
  src/main/java/com/playus/userservice/domain/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/playus/userservice/domain/oauth/service/TokenService.java
  src/main/java/com/playus/userservice/domain/oauth/specification/AuthControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/controller/FavoriteTeamController.java
  src/main/java/com/playus/userservice/domain/user/controller/ProfileSetupController.java
  src/main/java/com/playus/userservice/domain/user/controller/UserController.java
  src/main/java/com/playus/userservice/domain/user/dto/favoriteteam/FavoriteTeamRequest.java
  src/main/java/com/playus/userservice/domain/user/dto/favoriteteam/FavoriteTeamResponse.java
  src/main/java/com/playus/userservice/domain/user/dto/nickname/NicknameRequest.java
  src/main/java/com/playus/userservice/domain/user/dto/nickname/NicknameResponse.java
  src/main/java/com/playus/userservice/domain/user/dto/profilesetup/UserRegisterRequest.java
  src/main/java/com/playus/userservice/domain/user/dto/profilesetup/UserRegisterResponse.java
  src/main/java/com/playus/userservice/domain/user/entity/FavoriteTeam.java
  src/main/java/com/playus/userservice/domain/user/entity/User.java
  src/main/java/com/playus/userservice/domain/user/enums/Team.java
  src/main/java/com/playus/userservice/domain/user/repository/write/FavoriteTeamRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/write/UserRepository.java
  src/main/java/com/playus/userservice/domain/user/service/FavoriteTeamService.java
  src/main/java/com/playus/userservice/domain/user/service/ProfileSetupService.java
  src/main/java/com/playus/userservice/domain/user/service/UserService.java
  src/main/java/com/playus/userservice/domain/user/specification/FavoriteTeamControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/ProfileSetupControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/UserControllerSpecification.java
  src/main/java/com/playus/userservice/global/config/SecurityConfig.java
  src/main/java/com/playus/userservice/global/config/sentry/SentryConfig.java
  src/main/java/com/playus/userservice/global/config/swagger/SwaggerConfig.java
  src/main/java/com/playus/userservice/global/exception/ExceptionAdvice.java
  src/main/java/com/playus/userservice/global/jwt/JwtFilter.java
  src/main/java/com/playus/userservice/global/jwt/JwtUtil.java
  src/main/resources/application-local.yaml
  src/main/resources/application-test.yaml
  src/test/java/com/playus/userservice/ControllerTestSupport.java
  src/test/java/com/playus/userservice/IntegrationTestSupport.java
  src/test/java/com/playus/userservice/OpenFeignClientTestSupport.java
  src/test/java/com/playus/userservice/domain/user/controller/FavoriteTeamControllerTest.java
  src/test/java/com/playus/userservice/domain/user/controller/ProfileSetupControllerTest.java
  src/test/java/com/playus/userservice/domain/user/controller/UserControllerTest.java
  src/test/java/com/playus/userservice/domain/user/repository/write/FavoriteTeamRepositoryTest.java
  src/test/java/com/playus/userservice/domain/user/service/FavoriteTeamServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/ProfileSetupServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserServiceTest.java
Labels: ✨ feature

#35 Cs 276 feat/사용자 정보 조회
  build.gradle
  src/main/java/com/playus/userservice/domain/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/playus/userservice/domain/oauth/service/AuthService.java
  src/main/java/com/playus/userservice/domain/oauth/service/TokenService.java
  src/main/java/com/playus/userservice/domain/user/controller/ProfileSetupController.java
  src/main/java/com/playus/userservice/domain/user/controller/UserController.java
  src/main/java/com/playus/userservice/domain/user/controller/UserProfileController.java
  src/main/java/com/playus/userservice/domain/user/document/FavoriteTeamDocument.java
  src/main/java/com/playus/userservice/domain/user/dto/UserDto.java
  src/main/java/com/playus/userservice/domain/user/dto/UserWithdrawResponse.java
  src/main/java/com/playus/userservice/domain/user/dto/presigned/PresignedUrlForSaveImageRequest.java
  src/main/java/com/playus/userservice/domain/user/dto/presigned/PresignedUrlForSaveImageResponse.java
  src/main/java/com/playus/userservice/domain/user/dto/profile/FavoriteTeamDto.java
  src/main/java/com/playus/userservice/domain/user/dto/profile/UserProfileResponse.java
  src/main/java/com/playus/userservice/domain/user/dto/profilesetup/UserRegisterRequest.java
  src/main/java/com/playus/userservice/domain/user/entity/User.java
  src/main/java/com/playus/userservice/domain/user/enums/AuthProvider.java
  src/main/java/com/playus/userservice/domain/user/repository/read/FavoriteTeamReadOnlyRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/read/UserReadOnlyRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/write/FavoriteTeamRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/write/UserRepository.java
  src/main/java/com/playus/userservice/domain/user/service/FavoriteTeamService.java
  src/main/java/com/playus/userservice/domain/user/service/ProfileSetupService.java
  src/main/java/com/playus/userservice/domain/user/service/UserProfileReadService.java
  src/main/java/com/playus/userservice/domain/user/service/UserService.java
  src/main/java/com/playus/userservice/domain/user/specification/FavoriteTeamControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/ProfileSetupControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/UserControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/UserProfileControllerSpecification.java
  src/main/java/com/playus/userservice/global/config/SecurityConfig.java
  src/main/java/com/playus/userservice/global/exception/ExceptionAdvice.java
  src/main/java/com/playus/userservice/global/jwt/JwtFilter.java
  src/main/java/com/playus/userservice/global/jwt/JwtUtil.java
  src/main/java/com/playus/userservice/global/s3/S3Config.java
  src/main/java/com/playus/userservice/global/s3/S3Service.java
  src/main/java/com/playus/userservice/global/util/AgeUtils.java
  src/main/resources/application-local.yaml
  src/main/resources/application-test.yaml
  src/test/java/com/playus/userservice/ControllerTestSupport.java
  src/test/java/com/playus/userservice/IntegrationTestSupport.java
  src/test/java/com/playus/userservice/domain/user/controller/ProfileSetupControllerTest.java
  src/test/java/com/playus/userservice/domain/user/controller/UserControllerTest.java
  src/test/java/com/playus/userservice/domain/user/controller/UserProfileControllerTest.java
  src/test/java/com/playus/userservice/domain/user/service/FavoriteTeamServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/ProfileSetupServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserProfileReadServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserServiceTest.java
Labels: ✨ feature, ✅ test

#39 Cs 298 feat/알림 기능 추가
  src/main/java/com/playus/userservice/domain/notification/controller/NotificationApiController.java
  src/main/java/com/playus/userservice/domain/notification/controller/NotificationController.java
  src/main/java/com/playus/userservice/domain/notification/dto/request/NoticeRequest.java
  src/main/java/com/playus/userservice/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/playus/userservice/domain/notification/repository/EmitterRepository.java
  src/main/java/com/playus/userservice/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/playus/userservice/domain/notification/service/NotificationService.java
  src/main/java/com/playus/userservice/domain/notification/specification/NotificationApiControllerSpecification.java
  src/main/java/com/playus/userservice/domain/notification/specification/NotificationControllerSpecification.java
  src/main/java/com/playus/userservice/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/playus/userservice/domain/user/controller/PartyApplicationController.java
  src/main/java/com/playus/userservice/domain/user/document/NotificationDocument.java
  src/main/java/com/playus/userservice/domain/user/document/UserDocument.java
  src/main/java/com/playus/userservice/domain/user/entity/Notification.java
  src/main/java/com/playus/userservice/domain/user/entity/User.java
  src/main/java/com/playus/userservice/domain/user/enums/NotificationType.java
  src/main/java/com/playus/userservice/domain/user/enums/Type.java
  src/main/java/com/playus/userservice/domain/user/feign/client/CommunityFeignClient.java
  src/main/java/com/playus/userservice/domain/user/feign/client/TwpFeignClient.java
  src/main/java/com/playus/userservice/domain/user/feign/fallback/CommunityFeignFallback.java
  src/main/java/com/playus/userservice/domain/user/feign/fallback/TwpFeignFallback.java
  src/main/java/com/playus/userservice/domain/user/feign/response/CommentNotificationEvent.java
  src/main/java/com/playus/userservice/domain/user/feign/response/PartyApplicationInfoFeignResponse.java
  src/main/java/com/playus/userservice/domain/user/feign/response/PartyNotificationEvent.java
  src/main/java/com/playus/userservice/domain/user/repository/write/NotificationRepository.java
  src/main/java/com/playus/userservice/domain/user/service/FavoriteTeamService.java
  src/main/java/com/playus/userservice/domain/user/service/UserProfileReadService.java
  src/main/java/com/playus/userservice/domain/user/service/UserService.java
  src/main/java/com/playus/userservice/global/config/SecurityConfig.java
  src/main/java/com/playus/userservice/global/jwt/JwtFilter.java
  src/main/java/com/playus/userservice/global/s3/S3Config.java
  src/main/resources/application-local.yaml
  src/main/resources/application-test.yaml
  src/test/java/com/playus/userservice/ControllerTestSupport.java
  src/test/java/com/playus/userservice/domain/notification/controller/NotificationApiControllerTest.java
  src/test/java/com/playus/userservice/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/playus/userservice/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserProfileReadServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserServiceTest.java
Labels: ✨ feature

#41 Cs 318 feat/유저 태그(직관팟 종료후 평가) 기능추가
  src/main/java/com/playus/userservice/domain/oauth/controller/TokenValidationController.java
  src/main/java/com/playus/userservice/domain/oauth/service/TokenValidationService.java
  src/main/java/com/playus/userservice/domain/oauth/specification/TokenValidationControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/controller/UserReviewController.java
  src/main/java/com/playus/userservice/domain/user/controller/UserTagReadController.java
  src/main/java/com/playus/userservice/domain/user/dto/UserReviewRequest.java
  src/main/java/com/playus/userservice/domain/user/dto/UserTagSummaryResponse.java
  src/main/java/com/playus/userservice/domain/user/dto/partyuser/PartyWriterInfoFeignResponse.java
  src/main/java/com/playus/userservice/domain/user/entity/UserTag.java
  src/main/java/com/playus/userservice/domain/user/repository/read/TagDocumentRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/read/UserTagDocumentRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/write/TagRepository.java
  src/main/java/com/playus/userservice/domain/user/repository/write/UserTagRepository.java
  src/main/java/com/playus/userservice/domain/user/service/UserProfileReadService.java
  src/main/java/com/playus/userservice/domain/user/service/UserReviewService.java
  src/main/java/com/playus/userservice/domain/user/service/UserTagReadService.java
  src/main/java/com/playus/userservice/domain/user/specification/UserProfileControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/UserReviewControllerSpecification.java
  src/main/java/com/playus/userservice/domain/user/specification/UserTagReadControllerSpecification.java
  src/main/java/com/playus/userservice/global/exception/ExceptionAdvice.java
  src/main/java/com/playus/userservice/global/request/TokenValidationRequest.java
  src/main/java/com/playus/userservice/global/response/TokenValidationResponse.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/test/java/com/playus/userservice/ControllerTestSupport.java
  src/test/java/com/playus/userservice/domain/user/controller/PartyUserControllerTest.java
  src/test/java/com/playus/userservice/domain/user/controller/UserReviewControllerTest.java
  src/test/java/com/playus/userservice/domain/user/controller/UserTagReadControllerTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserReviewServiceTest.java
  src/test/java/com/playus/userservice/domain/user/service/UserTagReadServiceTest.java
Labels: ✨ feature, ✅ test

#47 CS-339 Fix/JavaScript Cookie 사용불가 오류 수정
  src/main/java/com/playus/userservice/domain/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/playus/userservice/domain/oauth/service/AuthService.java
  src/main/java/com/playus/userservice/domain/oauth/service/TokenService.java
  src/main/java/com/playus/userservice/domain/user/controller/UserProfileController.java
Labels: 예찬, 🐛 bug
